# Generated by Django 4.2.2 on 2023-07-03 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='rolesxUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRole', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='extendedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeUser', models.CharField(default='<NoCode>', max_length=16)),
                ('nameUser', models.CharField(default='<NoName>', max_length=32)),
                ('lastnameUser', models.CharField(default='<NoLastName>', max_length=32)),
                ('phoneUser', models.CharField(default='<NoPhone>', max_length=12)),
                ('asociatedUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roleUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usersMetalprotec.rolesxuser')),
            ],
        ),
    ]
