# Generated by Django 4.2.2 on 2023-07-04 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProduct', models.CharField(blank=True, max_length=64, null=True)),
                ('codeProduct', models.CharField(blank=True, max_length=24, null=True)),
                ('codeSunatProduct', models.CharField(blank=True, max_length=24, null=True)),
                ('categoryProduct', models.CharField(blank=True, max_length=16, null=True)),
                ('subCategoryProduct', models.CharField(blank=True, max_length=16, null=True)),
                ('measureUnit', models.CharField(blank=True, max_length=16, null=True)),
                ('currencyProduct', models.CharField(blank=True, max_length=16, null=True)),
                ('weightProduct', models.CharField(blank=True, max_length=16, null=True)),
                ('pcnIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('pccIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('pvnIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('pvcIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('endpointProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='storeSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStore', models.CharField(blank=True, max_length=16, null=True)),
                ('dateCreation', models.DateField(blank=True, null=True)),
                ('endpointStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='storexproductSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatityProduct', models.CharField(blank=True, max_length=16, null=True)),
                ('asociatedProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.productsystem')),
                ('asociatedStore', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.storesystem')),
            ],
        ),
    ]
