# Generated by Django 4.2.2 on 2023-07-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('productsMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storexproductsystem',
            old_name='quatityProduct',
            new_name='quantityProduct',
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='endpointProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem'),
        ),
        migrations.AlterField(
            model_name='storesystem',
            name='endpointStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem'),
        ),
        migrations.AlterField(
            model_name='storexproductsystem',
            name='asociatedProduct',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsMetalprotec.productsystem'),
        ),
        migrations.AlterField(
            model_name='storexproductsystem',
            name='asociatedStore',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='productsMetalprotec.storesystem'),
        ),
    ]
