# Generated by Django 4.2.2 on 2023-07-16 07:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsMetalprotec', '0002_rename_quatityproduct_storexproductsystem_quantityproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsystem',
            name='kitInfo',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='productsystem',
            name='kitProduct',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
