# Generated by Django 4.2.2 on 2023-07-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsMetalprotec', '0004_alter_productsystem_categoryproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='categoryProduct',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='codeProduct',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='codeSunatProduct',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='nameProduct',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='productsystem',
            name='subCategoryProduct',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
