# Generated by Django 4.2.2 on 2023-07-16 18:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productsMetalprotec', '0005_alter_productsystem_categoryproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsystem',
            name='kitInfo',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12), blank=True, null=True, size=None), blank=True, null=True, size=None),
        ),
    ]
