# Generated by Django 4.2.2 on 2023-07-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoryCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='divisionCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDivision', models.CharField(blank=True, max_length=32, null=True)),
                ('typeCost', models.CharField(blank=True, max_length=16, null=True)),
                ('behavior', models.CharField(blank=True, max_length=16, null=True)),
                ('operativeCost', models.CharField(blank=True, max_length=8, null=True)),
                ('asociatedCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesMetalprotec.categorycost')),
            ],
        ),
        migrations.CreateModel(
            name='departmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameDeparment', models.CharField(blank=True, max_length=32, null=True)),
                ('endpointDeparment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.AddField(
            model_name='categorycost',
            name='asociatedDeparment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesMetalprotec.departmentcost'),
        ),
    ]
