# Generated by Django 4.2.2 on 2023-07-09 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('expensesMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycost',
            name='endpointCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem'),
        ),
        migrations.AddField(
            model_name='divisioncost',
            name='endpointDivision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem'),
        ),
    ]
