# Generated by Django 4.2.2 on 2023-07-09 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('expensesMetalprotec', '0002_categorycost_endpointcategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='boxRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionBox', models.CharField(blank=True, max_length=32, null=True)),
                ('valueBox', models.CharField(blank=True, max_length=16, null=True)),
                ('creationDate', models.DateField(blank=True, null=True)),
                ('currencyBox', models.CharField(blank=True, max_length=8, null=True)),
                ('endpointBox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='costRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateField(blank=True, null=True)),
                ('documentCost', models.CharField(blank=True, max_length=16, null=True)),
                ('rucCost', models.CharField(blank=True, max_length=12, null=True)),
                ('identificationCost', models.CharField(blank=True, max_length=64, null=True)),
                ('descriptionCost', models.CharField(blank=True, max_length=64, null=True)),
                ('quantityCost', models.CharField(blank=True, max_length=12, null=True)),
                ('currencyCost', models.CharField(blank=True, max_length=8, null=True)),
                ('asociatedBox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expensesMetalprotec.boxregister')),
                ('asociatedDivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expensesMetalprotec.divisioncost')),
                ('endpointCost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='cashIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateField(blank=True, null=True)),
                ('descriptionIncome', models.CharField(blank=True, max_length=48, null=True)),
                ('quantityIncome', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedBox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expensesMetalprotec.boxregister')),
                ('endpointIncome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
    ]
