# Generated by Django 4.2.2 on 2023-07-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='endpointSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeEndpoint', models.CharField(blank=True, max_length=8, null=True)),
                ('serieCoti', models.CharField(blank=True, max_length=8, null=True)),
                ('nroCoti', models.CharField(blank=True, max_length=16, null=True)),
                ('serieGuia', models.CharField(blank=True, max_length=8, null=True)),
                ('nroGuia', models.CharField(blank=True, max_length=16, null=True)),
                ('serieFactura', models.CharField(blank=True, max_length=8, null=True)),
                ('nroFactura', models.CharField(blank=True, max_length=16, null=True)),
                ('serieBoleta', models.CharField(blank=True, max_length=8, null=True)),
                ('nroBoleta', models.CharField(blank=True, max_length=16, null=True)),
                ('serieNotaFactura', models.CharField(blank=True, max_length=8, null=True)),
                ('nroNotaFactura', models.CharField(blank=True, max_length=16, null=True)),
                ('serieNotaBoleta', models.CharField(blank=True, max_length=8, null=True)),
                ('nroNotaBoleta', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
