# Generated by Django 4.2.2 on 2023-07-04 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='serviceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameService', models.CharField(blank=True, max_length=64, null=True)),
                ('categoryService', models.CharField(blank=True, max_length=16, null=True)),
                ('subCategoryService', models.CharField(blank=True, max_length=16, null=True)),
                ('measureUnit', models.CharField(blank=True, max_length=16, null=True)),
                ('pvnIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('pvcIGV', models.CharField(blank=True, max_length=16, null=True)),
                ('endpointService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
    ]
