# Generated by Django 4.2.2 on 2023-07-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesystem',
            name='currencyService',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
