# Generated by Django 4.2.2 on 2023-07-05 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('servicesMetalprotec', '0002_servicesystem_currencyservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesystem',
            name='endpointService',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem'),
        ),
    ]
