# Generated by Django 4.2 on 2023-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicesMetalprotec', '0003_alter_servicesystem_endpointservice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesystem',
            name='categoryService',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='servicesystem',
            name='subCategoryService',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
