# Generated by Django 4.2.2 on 2023-07-05 07:44

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsMetalprotec', '0002_rename_quatityproduct_storexproductsystem_quantityproduct_and_more'),
        ('servicesMetalprotec', '0003_alter_servicesystem_endpointservice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clientsMetalprotec', '0001_initial'),
        ('settingsMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='quotationSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showDiscount', models.CharField(blank=True, max_length=4, null=True)),
                ('showUnitPrice', models.CharField(blank=True, max_length=4, null=True)),
                ('showSellPrice', models.CharField(blank=True, max_length=4, null=True)),
                ('relatedDocumentQuotation', models.CharField(blank=True, max_length=12, null=True)),
                ('commentQuotation', models.CharField(blank=True, max_length=256, null=True)),
                ('quotesQuotation', models.CharField(blank=True, max_length=4, null=True)),
                ('expirationCredit', models.CharField(blank=True, max_length=4, null=True)),
                ('expirationQuotation', models.CharField(blank=True, max_length=4, null=True)),
                ('numberQuotation', models.CharField(blank=True, max_length=8, null=True)),
                ('erBuy', models.CharField(blank=True, max_length=8, null=True)),
                ('erSel', models.CharField(blank=True, max_length=8, null=True)),
                ('codeQuotation', models.CharField(blank=True, max_length=16, null=True)),
                ('stateQuotation', models.CharField(blank=True, max_length=12, null=True)),
                ('paymentQuotation', models.CharField(blank=True, max_length=12, null=True)),
                ('dateQuotation', models.DateField(blank=True, null=True)),
                ('typeQuotation', models.CharField(blank=True, max_length=12, null=True)),
                ('currencyQuotation', models.CharField(blank=True, max_length=12, null=True)),
                ('endpointQuotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='quotationServiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataServiceQuotation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('asociatedQuotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem')),
                ('asociatedService', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicesMetalprotec.servicesystem')),
            ],
        ),
        migrations.CreateModel(
            name='quotationSellerData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataUserQuotation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('asociatedQuotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem')),
                ('asociatedUser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='quotationProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataProductQuotation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('asociatedProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.productsystem')),
                ('asociatedQuotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem')),
            ],
        ),
        migrations.CreateModel(
            name='quotationClientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataClientQuotation', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('asociatedClient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientsMetalprotec.clientsystem')),
                ('asociatedQuotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem')),
            ],
        ),
    ]
