# Generated by Django 4.2.2 on 2023-07-10 21:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('salesMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='billSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentBill', models.CharField(blank=True, max_length=256, null=True)),
                ('dateBill', models.DateField(blank=True, null=True)),
                ('relatedDocumentBill', models.CharField(blank=True, max_length=24, null=True)),
                ('dateQuotesBill', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('erBuy', models.CharField(blank=True, max_length=8, null=True)),
                ('erSel', models.CharField(blank=True, max_length=8, null=True)),
                ('currencyBill', models.CharField(blank=True, max_length=12, null=True)),
                ('stateBill', models.CharField(blank=True, max_length=12, null=True)),
                ('endpointGuide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.AddField(
            model_name='quotationproductdata',
            name='weightProduct',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.CreateModel(
            name='invoiceSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentInvoice', models.CharField(blank=True, max_length=256, null=True)),
                ('dateInvoice', models.DateField(blank=True, null=True)),
                ('relatedDocumentInvoice', models.CharField(blank=True, max_length=24, null=True)),
                ('dateQuotesInvoice', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), blank=True, null=True, size=None)),
                ('erBuy', models.CharField(blank=True, max_length=8, null=True)),
                ('erSel', models.CharField(blank=True, max_length=8, null=True)),
                ('currencyInvoice', models.CharField(blank=True, max_length=12, null=True)),
                ('stateInvoice', models.CharField(blank=True, max_length=12, null=True)),
                ('endpointGuide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='guideSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentGuide', models.CharField(blank=True, max_length=256, null=True)),
                ('dateGuide', models.DateField(blank=True, null=True)),
                ('dateGivenGoods', models.DateField(blank=True, null=True)),
                ('purposeTransportation', models.CharField(blank=True, max_length=16, null=True)),
                ('modeTransportation', models.CharField(blank=True, max_length=12, null=True)),
                ('extraWeight', models.CharField(blank=True, max_length=8, null=True)),
                ('ubigeoClient', models.CharField(blank=True, max_length=12, null=True)),
                ('deparmentDeparture', models.CharField(blank=True, max_length=24, null=True)),
                ('provinceDeparture', models.CharField(blank=True, max_length=24, null=True)),
                ('districtDeparture', models.CharField(blank=True, max_length=24, null=True)),
                ('addressDeparture', models.CharField(blank=True, max_length=256, null=True)),
                ('ubigeoDeparture', models.CharField(blank=True, max_length=12, null=True)),
                ('razonSocialTranporter', models.CharField(blank=True, max_length=256, null=True)),
                ('rucTransporter', models.CharField(blank=True, max_length=12, null=True)),
                ('vehiclePlate', models.CharField(blank=True, max_length=12, null=True)),
                ('dniDriver', models.CharField(blank=True, max_length=12, null=True)),
                ('licenceDriver', models.CharField(blank=True, max_length=12, null=True)),
                ('nameDriver', models.CharField(blank=True, max_length=64, null=True)),
                ('stateGuide', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.billsystem')),
                ('asociatedInvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.invoicesystem')),
                ('asociatedQuotation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem')),
                ('endpointGuide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
        migrations.CreateModel(
            name='creditNoteSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeCreditNote', models.CharField(blank=True, max_length=12, null=True)),
                ('stateCreditNote', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedBill', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.billsystem')),
                ('asociatedInvoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.invoicesystem')),
            ],
        ),
    ]
