# Generated by Django 4.2.2 on 2023-07-10 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0003_billsystem_codebill_creditnotesystem_codecreditnote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='creditnotesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='guidesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
