# Generated by Django 4.2.2 on 2023-07-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0004_billsystem_statetefacturo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotesystem',
            name='dateCreditNote',
            field=models.DateField(blank=True, null=True),
        ),
    ]
