# Generated by Django 4.2.2 on 2023-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0005_creditnotesystem_datecreditnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsystem',
            name='nroBill',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='creditnotesystem',
            name='nroCreditNote',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='guidesystem',
            name='nroGuide',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicesystem',
            name='nroInvoice',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
