# Generated by Django 4.2.2 on 2023-07-11 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0006_billsystem_nrobill_creditnotesystem_nrocreditnote_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billsystem',
            old_name='endpointGuide',
            new_name='endpointBill',
        ),
        migrations.RenameField(
            model_name='creditnotesystem',
            old_name='endpointGuide',
            new_name='endpointCreditNote',
        ),
        migrations.RenameField(
            model_name='invoicesystem',
            old_name='endpointGuide',
            new_name='endpointInvoice',
        ),
    ]
