# Generated by Django 4.2.2 on 2023-07-14 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0007_rename_endpointguide_billsystem_endpointbill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsystem',
            name='asociatedQuotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem'),
        ),
        migrations.AddField(
            model_name='billsystem',
            name='originBill',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='billsystem',
            name='typeItemsBill',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
