# Generated by Django 4.2.2 on 2023-07-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0008_billsystem_asociatedquotation_billsystem_originbill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesystem',
            name='asociatedQuotation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salesMetalprotec.quotationsystem'),
        ),
        migrations.AddField(
            model_name='invoicesystem',
            name='originInvoice',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='invoicesystem',
            name='typeItemsInvoice',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
