# Generated by Django 4.2.2 on 2023-07-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0009_invoicesystem_asociatedquotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billsystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='creditnotesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='guidesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='invoicesystem',
            name='stateTeFacturo',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
