# Generated by Django 4.2.2 on 2023-07-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0012_alter_quotationsystem_relateddocumentquotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidesystem',
            name='purposeTransportation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
