# Generated by Django 4.2 on 2023-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0015_billsystem_paidbill_billsystem_stockbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicesystem',
            name='paidInvoice',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='invoicesystem',
            name='stockInvoice',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
