# Generated by Django 4.2 on 2023-09-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0016_invoicesystem_paidinvoice_invoicesystem_stockinvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotesystem',
            name='creditNotePurpose',
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
    ]
