# Generated by Django 4.2 on 2023-11-29 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0019_guidesystem_statediscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditnotesystem',
            name='stockCreditNote',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
