# Generated by Django 4.2.2 on 2023-07-12 16:43

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productsMetalprotec', '0002_rename_quatityproduct_storexproductsystem_quantityproduct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('salesMetalprotec', '0007_rename_endpointguide_billsystem_endpointbill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockTakingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateStockTaking', models.DateField(blank=True, null=True)),
                ('codeStockTaking', models.CharField(blank=True, max_length=12, null=True)),
                ('stateStockTaking', models.CharField(blank=True, max_length=12, null=True)),
                ('storeStokTaking', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedStoreData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.storesystem')),
                ('asociatedUserData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='outcomingItemsRegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeOutcoming', models.CharField(blank=True, max_length=12, null=True)),
                ('dateOutcoming', models.DateField(blank=True, null=True)),
                ('productCode', models.CharField(blank=True, max_length=24, null=True)),
                ('nameStore', models.CharField(blank=True, max_length=12, null=True)),
                ('quantityProduct', models.CharField(blank=True, max_length=12, null=True)),
                ('lastStock', models.CharField(blank=True, max_length=12, null=True)),
                ('newStock', models.CharField(blank=True, max_length=12, null=True)),
                ('referenceOutcome', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedBill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.billsystem')),
                ('asociatedInvoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.invoicesystem')),
                ('asociatedProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.productsystem')),
                ('asociatedStoreData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.storesystem')),
                ('asociatedUserData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='infoStockTaking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataStockTakingInfo', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=128), blank=True, null=True, size=None)),
                ('asociatedProsductInfo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.productsystem')),
                ('asociatedStockTaking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockManagment.stocktakingdata')),
            ],
        ),
        migrations.CreateModel(
            name='incomingItemsRegisterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIncoming', models.CharField(blank=True, max_length=12, null=True)),
                ('dateIncoming', models.DateField(blank=True, null=True)),
                ('productCode', models.CharField(blank=True, max_length=24, null=True)),
                ('nameStore', models.CharField(blank=True, max_length=12, null=True)),
                ('quantityProduct', models.CharField(blank=True, max_length=12, null=True)),
                ('lastStock', models.CharField(blank=True, max_length=12, null=True)),
                ('newStock', models.CharField(blank=True, max_length=12, null=True)),
                ('referenceIncome', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedCreditNote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.creditnotesystem')),
                ('asociatedProduct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.productsystem')),
                ('asociatedStoreData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productsMetalprotec.storesystem')),
                ('asociatedUserData', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
