# Generated by Django 4.2.2 on 2023-07-13 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('stockManagment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemsregisterinfo',
            name='endpointIncoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem'),
        ),
        migrations.AddField(
            model_name='outcomingitemsregisterinfo',
            name='endpointOutcoming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem'),
        ),
        migrations.AddField(
            model_name='stocktakingdata',
            name='endpointStockTaking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem'),
        ),
    ]
