# Generated by Django 4.2.2 on 2023-07-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockManagment', '0004_alter_incomingitemsregisterinfo_laststock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='lastStock',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='nameStore',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='newStock',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='quantityProduct',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='referenceOutcome',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='outcomingitemsregisterinfo',
            name='typeOutcoming',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
