# Generated by Django 4.2 on 2023-10-29 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0019_guidesystem_statediscount'),
        ('stockManagment', '0005_alter_outcomingitemsregisterinfo_laststock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemsregisterinfo',
            name='asociatedBill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.billsystem'),
        ),
    ]
