# Generated by Django 4.2 on 2023-10-30 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesMetalprotec', '0019_guidesystem_statediscount'),
        ('stockManagment', '0006_incomingitemsregisterinfo_asociatedbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomingitemsregisterinfo',
            name='asociatedInvoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesMetalprotec.invoicesystem'),
        ),
    ]
