# Generated by Django 4.2.2 on 2023-07-14 03:51

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settingsMetalprotec', '0001_initial'),
        ('financeMetalprotec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='settingsComission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateRegistered', models.DateField(blank=True, null=True)),
                ('igvIncluded', models.CharField(blank=True, max_length=10, null=True)),
                ('percentageComision', models.CharField(blank=True, max_length=10, null=True)),
                ('typeComission', models.CharField(blank=True, max_length=12, null=True)),
                ('comissionCode', models.CharField(blank=True, max_length=12, null=True)),
                ('asociatedUsers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=8), blank=True, null=True, size=None)),
                ('endpointComission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='settingsMetalprotec.endpointsystem')),
            ],
        ),
    ]
