# Generated by Django 4.2 on 2023-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeMetalprotec', '0002_settingscomission'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='operationNumber2',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
