# Generated by Django 4.2 on 2023-07-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeMetalprotec', '0003_paymentsystem_operationnumber2'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentsystem',
            name='enabledComission',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
